### PR TITLE
add watch task

### PR DESCRIPTION
**Pull request by eymen-elkum**
this was very helpful! and keep the one direction logic

I liked to share it with community

### CODE REVIEW

**Comment by eymen-elkum** [comment]
#2

**Comment by yurikuzn** [comment]
Could you elaborate how this works please?

**Comment by eymen-elkum** [comment]
Sure!

It is about skipping the step#2 in the [development proccess here](https://github.com/espocrm/ext-template/blob/master/README.md#development-workflow)

So any change saved to the src files will automatically copied to the site

**Comment by yurikuzn** [comment]
When you run `node build --watch` does it block the terminal? And while it's running it's doing its job copying files when they're changed?

**Comment by eymen-elkum** [comment]
Yes, I have just tested and sounds there is an infinity loop, I remember that I fixed it somedays later from this PR but on another place where I was working on a real extension.

Will check and back to you

**Comment by eymen-elkum** [comment]
I think that this feature is something must to have in this template, as it is painful to run copy command everytime you make a change on src files

**Comment by eymen-elkum** [comment]
If you like I can squach the commits into one commit

**Comment by yurikuzn** [comment]
Could not make it to work on Ubuntu. Requires some tweaking in the system. Got *System limit for number of file watchers reached* error.

**Comment by eymen-elkum** [comment]
I am testing on mac and it is working fine here, not sure if will work for larger extensions

**Comment by yurikuzn** [comment]
I would suggest using file watcher functionality in IDE. This will be more useful as we move in JS transpiling direction.

**Comment by yurikuzn** [comment]
With the new extension-tools version: https://github.com/espocrm/ext-template?tab=readme-ov-file#file-watcher

**Comment by eymen-elkum** [comment]
Excellent 👏🏼

**Pull request closed without merging**
